# Generated by Django 5.1.2 on 2025-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0002_movie_rating_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Review',
            field=models.TextField(blank=True),
        ),
    ]
