# Generated by Django 5.1.2 on 2025-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0003_movie_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Genre', models.CharField(choices=[('F', 'Fantasy'), ('R', 'Romance'), ('D', 'Drama'), ('C', 'Comedy'), ('H', 'Horror'), ('A', 'Action'), ('M', 'Musical'), ('T', 'Thriller'), ('DOC', 'Documentary'), ('SF', 'ScienceFiction'), ('AM', 'Animation'), ('AD', 'Adventure')], max_length=3)),
                ('Episodes', models.IntegerField()),
                ('Rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('Review', models.TextField(blank=True)),
            ],
        ),
    ]
