# Generated by Django 5.1.2 on 2025-01-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0004_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='Episodes',
            new_name='Episodes_s',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Genre',
            new_name='Genre_s',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Name',
            new_name='Name_s',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Rating',
            new_name='Rating_s',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Review',
            new_name='Review_s',
        ),
    ]
