# Generated by Django 5.1.2 on 2025-01-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0005_rename_episodes_series_episodes_s_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='Episodes_s',
            new_name='Episodes_watched',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Genre_s',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Name_s',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Rating_s',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='Review_s',
            new_name='Review',
        ),
    ]
