# Generated by Django 5.1.2 on 2025-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_director_alter_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='year_born',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
