# Generated by Django 5.1.4 on 2025-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0010_alter_director_year_born'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_of_establishment', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=80)),
            ],
        ),
    ]
