# Generated by Django 5.1.2 on 2025-01-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0012_movie_director_movie_studio_series_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name']},
        ),
    ]
